### ISSUE TITLE
Add support for fish and zsh.

### ISSUE THREAD

**Issue by jiegec** [xyb/homebrew-cask-completion#1]
I prefer fish to bash. And zsh is popular too.

**Comment by xyb** [comment]
@jiegec Sure, I will try to add fish completion. But zsh supported by [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) which is [officially recommended by homebrew-cask maintainers](https://github.com/caskroom/homebrew-cask/pull/13785#issuecomment-141844184).

**Comment by xyb** [comment]
@jiegec I have release v2.0 which added support for fish.
