### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joshka** [xyb/homebrew-cask-completion#4]
Hi @xyb,
I'd like to incorporate your completions into homebrew directly per https://github.com/Homebrew/homebrew-services/pull/73#issuecomment-250699232

This code is currently licensed as MIT. Would you be willing to relicense it with the same license as Homebrew? (BSD 2 Clause): https://github.com/Homebrew/brew/tree/master/LICENSE.txt

**Comment by xyb** [comment]
@joshka, license changed already

**Comment by joshka** [comment]
Thanks @xyb, I'll get to this soon :)

**Comment by joshka** [comment]
Hiya,

My goal here is to deprecate this repository altogether, so that going forward it's not necessary to take extra steps to enable tab completion.

The licensing issue is a little more subtle than I'd previously thought about now that I think this through. Would you allow us to relicense this under Homebrew's license, by removing the copyright requirement mentioning your name. For reference the Homebrew copyright is "Copyright (c) 2009-2016, Homebrew contributors". I'd maintain the history of the files in this repository by doing a tree graft in git, so you'd maintain historical authorship of these files, but wouldn't be called out directly by name.

The other alternative would be to incorporate a copy of the license into the scripts as a comment. This would allow you to keep your name in the copyright text.

**Comment by xyb** [comment]
@joshka good to know, I've changed it to homebrew's format.  ^_^

**Comment by apjanke** [comment]
Hi, pinging on this due to recent Homebrew changes!

Homebrew has merged the `brew cask` functionality into core `brew`. But we don't have bash completion support for it, as noted in https://github.com/Homebrew/brew/issues/3625.

Just as a feeler: How would you feel about having your `homebrew-cask-completion.bash` merged in to the core `brew` bash completions, as a base for `brew`'s own completion support?

**Comment by apjanke** [comment]
BTW, this is what it would look like. Your author credit would be preserved in the commit history.

https://github.com/apjanke/brew/tree/cask-bash-completion

**Comment by xyb** [comment]
@apjanke That's great! Please let me know if there anything needs me to do.

**Comment by xyb** [comment]
@apjanke and the code are outdated, you may what to update subcommand list.

**Comment by apjanke** [comment]
Nothing you need to do! I will update the subcommand list and submit this as a PR with Homebrew. Thank you!

**Comment by apjanke** [comment]
PR was accepted; your code is now in core Homebrew! Thank you!
